version: '3.1'  # versao do docker compose

services: # containers do compose
  php: # container php
    build: # constroi a imagem do dockerfile
      context: . # diretório onde o dockerfile está
      dockerfile: Dockerfile
    ports: # recebe a porta 80 do container (porta default) e redireciona para a 8081 (porta da maquina)
      - 8081:80
    volumes: # pega o conteudo do site que esta no pc e envia para a pasta padrao do php apache
      - ./site-mar-azul:/var/www/html/

  phpmyadmin: # container phpmyadmin
    image: phpmyadmin #pega a imagem do phpmyadmin
    restart: always # define a reiniciação em caso de falha
    ports: # recebe a porta 80 do container phpmyadmin e retorna para 8082
      - 8082:80
    environment: #variaveis de ambiente necessarias para funcionamento do container phpmyadmin
      - PMA_ARBITRARY=1
  
  db: #container banco de dados
    image: mysql #pega a imagem do mysql
    command: --default-authentication-plugin=mysql_native_password  # aqui pode especificar comandos que serão executados quando o conteiner iniciar
    restart: always  # define a reiniciação em caso de falha
    environment:  #variaveis de ambiente necessarias para funcionamento do container mysql
      MYSQL_DATABASE: dbmarazul
      MYSQL_ROOT_PASSWORD: 12345
    volumes: 
      - "./dump:/docker-entrypoint-initdb.d" # execução de scripts sql ao iniciar o container
