version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./site-mar-azul:/var/www/html/

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: dbmarazul
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - "./dump:/docker-entrypoint-initdb.d"